### ISSUE TITLE
How could i change to MySQL

### ISSUE THREAD

**Issue by gablemos-zz** [esausilva/fullcalendar-aspnet-core#2]
I'm sorry, i'm a beginner developer and i'm using MySQL not Sql Server. It's hard to make this change? How could i do it?

**Comment by esausilva** [comment]
Well, I really haven't used MySQL, however I found [this tutorial](https://www.c-sharpcorner.com/article/how-to-connect-mysql-with-asp-net-core/) that seems to be pretty straight forward.

All you have to do is install **MySql.Data** NuGet package and then in `appsettings.json` change the connection string (`ConnectionStr`) to point to your MySQL database. Of course you will also need to create the necessary database and tables needed for the calendar.

Hope this helps

**Comment by esausilva** [comment]
Were you able to use MySQL instead of SQL Server?

**Comment by galemos** [comment]
No, so i change the project to SQL Server.
